In [1]:
import yfinance

Stock_Symbol = "BTC-USD"

Start_Date = "2020-01-01"

End_Date = "2025-01-01"

dataframe = yfinance.download(tickers = Stock_Symbol,
                             start = Start_Date,
                             end = End_Date)
dataframe

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,
2020-01-01,7200.174316,7254.330566,7174.944336,7194.892090,18565664997
2020-01-02,6985.470215,7212.155273,6935.270020,7202.551270,20802083465
2020-01-03,7344.884277,7413.715332,6914.996094,6984.428711,28111481032
2020-01-04,7410.656738,7427.385742,7309.514160,7345.375488,18444271275
2020-01-05,7411.317383,7544.497070,7400.535645,7410.451660,19725074095
...,...,...,...,...,...
2024-12-27,94164.859375,97294.843750,93310.742188,95704.976562,52419934565
2024-12-28,95163.929688,95525.898438,94014.289062,94160.187500,24107436185
2024-12-29,93530.226562,95174.875000,92881.789062,95174.054688,29635885267
2024-12-30,92643.210938,94903.320312,91317.132812,93527.195312,56188003691
2024-12-31,93429.203125,96090.601562,91914.031250,92643.250000,43625106843

In [2]:
import numpy as np

Decreased = 1

Increased = 0

dataframe["Volume Increase/Decrease"] = np.where(dataframe["Volume"].shift(-1) > dataframe["Volume"],
                                                Decreased,
                                                Increased)

dataframe

Price,Close,High,Low,Open,Volume,Volume Increase/Decrease
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD,
Date,,,,,,
2020-01-01,7200.174316,7254.330566,7174.944336,7194.892090,18565664997,1
2020-01-02,6985.470215,7212.155273,6935.270020,7202.551270,20802083465,1
2020-01-03,7344.884277,7413.715332,6914.996094,6984.428711,28111481032,0
2020-01-04,7410.656738,7427.385742,7309.514160,7345.375488,18444271275,1
2020-01-05,7411.317383,7544.497070,7400.535645,7410.451660,19725074095,1
...,...,...,...,...,...,...
2024-12-27,94164.859375,97294.843750,93310.742188,95704.976562,52419934565,0
2024-12-28,95163.929688,95525.898438,94014.289062,94160.187500,24107436185,1
2024-12-29,93530.226562,95174.875000,92881.789062,95174.054688,29635885267,1
2024-12-30,92643.210938,94903.320312,91317.132812,93527.195312,56188003691,0
2024-12-31,93429.203125,96090.601562,91914.031250,92643.250000,43625106843,0

In [3]:
dataframe["Returns"] = dataframe["Close"].pct_change()

dataframe

Price,Close,High,Low,Open,Volume,Volume Increase/Decrease,Returns
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD,,
Date,,,,,,,
2020-01-01,7200.174316,7254.330566,7174.944336,7194.892090,18565664997,1,NaN
2020-01-02,6985.470215,7212.155273,6935.270020,7202.551270,20802083465,1,-0.029819
2020-01-03,7344.884277,7413.715332,6914.996094,6984.428711,28111481032,0,0.051452
2020-01-04,7410.656738,7427.385742,7309.514160,7345.375488,18444271275,1,0.008955
2020-01-05,7411.317383,7544.497070,7400.535645,7410.451660,19725074095,1,0.000089
...,...,...,...,...,...,...,...
2024-12-27,94164.859375,97294.843750,93310.742188,95704.976562,52419934565,0,-0.017022
2024-12-28,95163.929688,95525.898438,94014.289062,94160.187500,24107436185,1,0.010610
2024-12-29,93530.226562,95174.875000,92881.789062,95174.054688,29635885267,1,-0.017167
2024-12-30,92643.210938,94903.320312,91317.132812,93527.195312,56188003691,0,-0.009484
2024-12-31,93429.203125,96090.601562,91914.031250,92643.250000,43625106843,0,0.008484

In [4]:
dataframe = dataframe.dropna()

dataframe

Price,Close,High,Low,Open,Volume,Volume Increase/Decrease,Returns
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD,,
Date,,,,,,,
2020-01-02,6985.470215,7212.155273,6935.270020,7202.551270,20802083465,1,-0.029819
2020-01-03,7344.884277,7413.715332,6914.996094,6984.428711,28111481032,0,0.051452
2020-01-04,7410.656738,7427.385742,7309.514160,7345.375488,18444271275,1,0.008955
2020-01-05,7411.317383,7544.497070,7400.535645,7410.451660,19725074095,1,0.000089
2020-01-06,7769.219238,7781.867188,7409.292969,7410.452148,23276261598,1,0.048291
...,...,...,...,...,...,...,...
2024-12-27,94164.859375,97294.843750,93310.742188,95704.976562,52419934565,0,-0.017022
2024-12-28,95163.929688,95525.898438,94014.289062,94160.187500,24107436185,1,0.010610
2024-12-29,93530.226562,95174.875000,92881.789062,95174.054688,29635885267,1,-0.017167
2024-12-30,92643.210938,94903.320312,91317.132812,93527.195312,56188003691,0,-0.009484
2024-12-31,93429.203125,96090.601562,91914.031250,92643.250000,43625106843,0,0.008484

In [5]:
Buy = 1

Sell = 0

dataframe["Buy/Sell"] = np.where(dataframe["Close"].shift(-1) > dataframe["Close"],
                                Buy,
                                Sell)
dataframe

C:\Users\David Moon\AppData\Local\Temp\ipykernel_90952\1048962053.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Buy/Sell"] = np.where(dataframe["Close"].shift(-1) > dataframe["Close"],

Price,Close,High,Low,Open,Volume,Volume Increase/Decrease,Returns,Buy/Sell
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD,,,
Date,,,,,,,,
2020-01-02,6985.470215,7212.155273,6935.270020,7202.551270,20802083465,1,-0.029819,1
2020-01-03,7344.884277,7413.715332,6914.996094,6984.428711,28111481032,0,0.051452,1
2020-01-04,7410.656738,7427.385742,7309.514160,7345.375488,18444271275,1,0.008955,1
2020-01-05,7411.317383,7544.497070,7400.535645,7410.451660,19725074095,1,0.000089,1
2020-01-06,7769.219238,7781.867188,7409.292969,7410.452148,23276261598,1,0.048291,1
...,...,...,...,...,...,...,...,...
2024-12-27,94164.859375,97294.843750,93310.742188,95704.976562,52419934565,0,-0.017022,1
2024-12-28,95163.929688,95525.898438,94014.289062,94160.187500,24107436185,1,0.010610,0
2024-12-29,93530.226562,95174.875000,92881.789062,95174.054688,29635885267,1,-0.017167,0
2024-12-30,92643.210938,94903.320312,91317.132812,93527.195312,56188003691,0,-0.009484,1
2024-12-31,93429.203125,96090.601562,91914.031250,92643.250000,43625106843,0,0.008484,0

In [6]:
dataframe["High vs Low"] = (dataframe["High"] - dataframe["Low"])/dataframe["Low"]

dataframe

C:\Users\David Moon\AppData\Local\Temp\ipykernel_90952\1102872069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["High vs Low"] = (dataframe["High"] - dataframe["Low"])/dataframe["Low"]

Price,Close,High,Low,Open,Volume,Volume Increase/Decrease,Returns,Buy/Sell,High vs Low
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD,,,,
Date,,,,,,,,,
2020-01-02,6985.470215,7212.155273,6935.270020,7202.551270,20802083465,1,-0.029819,1,0.039924
2020-01-03,7344.884277,7413.715332,6914.996094,6984.428711,28111481032,0,0.051452,1,0.072121
2020-01-04,7410.656738,7427.385742,7309.514160,7345.375488,18444271275,1,0.008955,1,0.016126
2020-01-05,7411.317383,7544.497070,7400.535645,7410.451660,19725074095,1,0.000089,1,0.019453
2020-01-06,7769.219238,7781.867188,7409.292969,7410.452148,23276261598,1,0.048291,1,0.050285
...,...,...,...,...,...,...,...,...,...
2024-12-27,94164.859375,97294.843750,93310.742188,95704.976562,52419934565,0,-0.017022,1,0.042697
2024-12-28,95163.929688,95525.898438,94014.289062,94160.187500,24107436185,1,0.010610,0,0.016079
2024-12-29,93530.226562,95174.875000,92881.789062,95174.054688,29635885267,1,-0.017167,0,0.024688
2024-12-30,92643.210938,94903.320312,91317.132812,93527.195312,56188003691,0,-0.009484,1,0.039272
2024-12-31,93429.203125,96090.601562,91914.031250,92643.250000,43625106843,0,0.008484,0,0.045440

In [7]:
dataframe["Open vs Close"] = (dataframe["Open"] - dataframe["Close"])/dataframe["Open"]

dataframe

C:\Users\David Moon\AppData\Local\Temp\ipykernel_90952\3471031492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Open vs Close"] = (dataframe["Open"] - dataframe["Close"])/dataframe["Open"]

Price,Close,High,Low,Open,Volume,Volume Increase/Decrease,Returns,Buy/Sell,High vs Low,Open vs Close
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD,,,,,
Date,,,,,,,,,,
2020-01-02,6985.470215,7212.155273,6935.270020,7202.551270,20802083465,1,-0.029819,1,0.039924,0.030139
2020-01-03,7344.884277,7413.715332,6914.996094,6984.428711,28111481032,0,0.051452,1,0.072121,-0.051608
2020-01-04,7410.656738,7427.385742,7309.514160,7345.375488,18444271275,1,0.008955,1,0.016126,-0.008887
2020-01-05,7411.317383,7544.497070,7400.535645,7410.451660,19725074095,1,0.000089,1,0.019453,-0.000117
2020-01-06,7769.219238,7781.867188,7409.292969,7410.452148,23276261598,1,0.048291,1,0.050285,-0.048414
...,...,...,...,...,...,...,...,...,...,...
2024-12-27,94164.859375,97294.843750,93310.742188,95704.976562,52419934565,0,-0.017022,1,0.042697,0.016092
2024-12-28,95163.929688,95525.898438,94014.289062,94160.187500,24107436185,1,0.010610,0,0.016079,-0.010660
2024-12-29,93530.226562,95174.875000,92881.789062,95174.054688,29635885267,1,-0.017167,0,0.024688,0.017272
2024-12-30,92643.210938,94903.320312,91317.132812,93527.195312,56188003691,0,-0.009484,1,0.039272,0.009452
2024-12-31,93429.203125,96090.601562,91914.031250,92643.250000,43625106843,0,0.008484,0,0.045440,-0.008484

In [8]:
X = np.array(dataframe.drop(["Buy/Sell"], axis = 1))

y = np.array(dataframe["Buy/Sell"])

X

array([[ 6.98547021e+03,  7.21215527e+03,  6.93527002e+03, ...,
        -2.98192922e-02,  3.99242211e-02,  3.01394668e-02],
       [ 7.34488428e+03,  7.41371533e+03,  6.91499609e+03, ...,
         5.14516634e-02,  7.21214056e-02, -5.16084538e-02],
       [ 7.41065674e+03,  7.42738574e+03,  7.30951416e+03, ...,
         8.95486688e-03,  1.61257752e-02, -8.88739454e-03],
       ...,
       [ 9.35302266e+04,  9.51748750e+04,  9.28817891e+04, ...,
        -1.71672516e-02,  2.46882189e-02,  1.72718093e-02],
       [ 9.26432109e+04,  9.49033203e+04,  9.13171328e+04, ...,
        -9.48373224e-03,  3.92717926e-02,  9.45162925e-03],
       [ 9.34292031e+04,  9.60906016e+04,  9.19140312e+04, ...,
         8.48407757e-03,  4.54399645e-02, -8.48365234e-03]])

In [9]:
y

array([1, 1, 1, ..., 0, 1, 0])

In [62]:
from sklearn.neural_network import BernoulliRBM

Number_Of_Components = 2

neural_network = BernoulliRBM(n_components = Number_Of_Components)

neural_network.fit(X)

BernoulliRBM(n_components=2)

In [63]:
neural_network.score_samples(X)

array([-6.23832463, -0.        , -0.        , ..., -6.23832463,
       -0.        , -6.23832463])

In [64]:
neural_network.transform(X)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [65]:
from sklearn.linear_model import LogisticRegression

logistic_regression = LogisticRegression()

neural_network_2 = BernoulliRBM(n_components = Number_Of_Components)

from sklearn.pipeline import Pipeline

classifier = Pipeline(steps = [("neural_network", neural_network_2), ("logistic_regresssion", logistic_regression)])

In [66]:
from sklearn.model_selection import train_test_split

Seed = 42

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = Seed)

In [67]:
X_train

array([[ 5.68049023e+04,  5.68331797e+04,  5.35550273e+04, ...,
         1.60570219e-02,  6.12109172e-02, -1.72654662e-02],
       [ 3.58677773e+04,  3.65421094e+04,  3.42524844e+04, ...,
         4.16282576e-02,  6.68455162e-02, -4.03827757e-02],
       [ 9.12341016e+03,  9.27496289e+03,  9.03662305e+03, ...,
        -1.13688060e-02,  2.63748795e-02,  1.16702267e-02],
       ...,
       [ 2.89363555e+04,  3.20134023e+04,  2.81704141e+04, ...,
        -6.72583917e-02,  1.36419304e-01,  6.70562230e-02],
       [ 4.22651875e+04,  4.28609375e+04,  4.19982539e+04, ...,
         2.56862222e-03,  2.05409395e-02, -2.68289955e-03],
       [ 2.37237695e+04,  2.37645391e+04,  2.28777500e+04, ...,
         2.52594829e-02,  3.87620751e-02, -2.53236126e-02]])

In [68]:
classifier.fit(X_train, y_train)

Pipeline(steps=[('neural_network', BernoulliRBM(n_components=2)),
                ('logistic_regresssion', LogisticRegression())])

In [69]:
predictions = classifier.predict(X_test)

predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [70]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, predictions)

0.49453551912568305